# Generated by Django 3.2.7 on 2022-04-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Text',
            new_name='Comment',
        ),
    ]
